default: &default
  adapter: postgresql
  encoding: unicode
  database: lunchbox_development
  username: lunchbox
  password: password
  host: localhost
  port: 5432

development:
  <<: *default

test:
  <<: *default
  database: lunchbox_test

production:
  <<: *default
  database: lunchbox_production